# .github/workflows/ci.yml
name: CI
on:
  push: 
    branches:
      - master 
jobs:
  deploy: # Nom du premier job
   runs-on: ubuntu-latest
   steps: 
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc" 
      - name: Install dependencies #Installation d√©pendance
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: npm run deploy
  test:
    needs: deploy
     runs-on: ubuntu-latest
    steps:
      name: test unitaire
      run: npm test
  lint:
    needs : deploy
     runs-on: ubuntu-latest
    steps:
      name: lint code
      run: npm run lint 
